// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: kmsp11/tools/p11fn/function_def.proto

package p11fnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CkFuncList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Functions []*CkFunc `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *CkFuncList) Reset() {
	*x = CkFuncList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmsp11_tools_p11fn_function_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CkFuncList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CkFuncList) ProtoMessage() {}

func (x *CkFuncList) ProtoReflect() protoreflect.Message {
	mi := &file_kmsp11_tools_p11fn_function_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CkFuncList.ProtoReflect.Descriptor instead.
func (*CkFuncList) Descriptor() ([]byte, []int) {
	return file_kmsp11_tools_p11fn_function_def_proto_rawDescGZIP(), []int{0}
}

func (x *CkFuncList) GetFunctions() []*CkFunc {
	if x != nil {
		return x.Functions
	}
	return nil
}

type CkFunc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args []*CkArg `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *CkFunc) Reset() {
	*x = CkFunc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmsp11_tools_p11fn_function_def_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CkFunc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CkFunc) ProtoMessage() {}

func (x *CkFunc) ProtoReflect() protoreflect.Message {
	mi := &file_kmsp11_tools_p11fn_function_def_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CkFunc.ProtoReflect.Descriptor instead.
func (*CkFunc) Descriptor() ([]byte, []int) {
	return file_kmsp11_tools_p11fn_function_def_proto_rawDescGZIP(), []int{1}
}

func (x *CkFunc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CkFunc) GetArgs() []*CkArg {
	if x != nil {
		return x.Args
	}
	return nil
}

type CkArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datatype string `protobuf:"bytes,1,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CkArg) Reset() {
	*x = CkArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmsp11_tools_p11fn_function_def_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CkArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CkArg) ProtoMessage() {}

func (x *CkArg) ProtoReflect() protoreflect.Message {
	mi := &file_kmsp11_tools_p11fn_function_def_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CkArg.ProtoReflect.Descriptor instead.
func (*CkArg) Descriptor() ([]byte, []int) {
	return file_kmsp11_tools_p11fn_function_def_proto_rawDescGZIP(), []int{2}
}

func (x *CkArg) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *CkArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_kmsp11_tools_p11fn_function_def_proto protoreflect.FileDescriptor

var file_kmsp11_tools_p11fn_function_def_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6b, 0x6d, 0x73, 0x70, 0x31, 0x31, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70,
	0x31, 0x31, 0x66, 0x6e, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x6b,
	0x6d, 0x73, 0x2e, 0x6b, 0x6d, 0x73, 0x70, 0x31, 0x31, 0x22, 0x44, 0x0a, 0x0a, 0x43, 0x6b, 0x46,
	0x75, 0x6e, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x5f, 0x6b, 0x6d, 0x73, 0x2e, 0x6b, 0x6d, 0x73, 0x70, 0x31, 0x31, 0x2e, 0x43, 0x6b,
	0x46, 0x75, 0x6e, 0x63, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x49, 0x0a, 0x06, 0x43, 0x6b, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5f, 0x6b, 0x6d, 0x73, 0x2e, 0x6b, 0x6d, 0x73, 0x70, 0x31, 0x31, 0x2e, 0x43,
	0x6b, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x37, 0x0a, 0x05, 0x43, 0x6b,
	0x41, 0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6d, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6b, 0x6d, 0x73, 0x70, 0x31, 0x31, 0x2f,
	0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x31, 0x31, 0x66, 0x6e, 0x2f, 0x70, 0x31, 0x31, 0x66,
	0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kmsp11_tools_p11fn_function_def_proto_rawDescOnce sync.Once
	file_kmsp11_tools_p11fn_function_def_proto_rawDescData = file_kmsp11_tools_p11fn_function_def_proto_rawDesc
)

func file_kmsp11_tools_p11fn_function_def_proto_rawDescGZIP() []byte {
	file_kmsp11_tools_p11fn_function_def_proto_rawDescOnce.Do(func() {
		file_kmsp11_tools_p11fn_function_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_kmsp11_tools_p11fn_function_def_proto_rawDescData)
	})
	return file_kmsp11_tools_p11fn_function_def_proto_rawDescData
}

var file_kmsp11_tools_p11fn_function_def_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kmsp11_tools_p11fn_function_def_proto_goTypes = []interface{}{
	(*CkFuncList)(nil), // 0: cloud_kms.kmsp11.CkFuncList
	(*CkFunc)(nil),     // 1: cloud_kms.kmsp11.CkFunc
	(*CkArg)(nil),      // 2: cloud_kms.kmsp11.CkArg
}
var file_kmsp11_tools_p11fn_function_def_proto_depIdxs = []int32{
	1, // 0: cloud_kms.kmsp11.CkFuncList.functions:type_name -> cloud_kms.kmsp11.CkFunc
	2, // 1: cloud_kms.kmsp11.CkFunc.args:type_name -> cloud_kms.kmsp11.CkArg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kmsp11_tools_p11fn_function_def_proto_init() }
func file_kmsp11_tools_p11fn_function_def_proto_init() {
	if File_kmsp11_tools_p11fn_function_def_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kmsp11_tools_p11fn_function_def_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CkFuncList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kmsp11_tools_p11fn_function_def_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CkFunc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kmsp11_tools_p11fn_function_def_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CkArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kmsp11_tools_p11fn_function_def_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kmsp11_tools_p11fn_function_def_proto_goTypes,
		DependencyIndexes: file_kmsp11_tools_p11fn_function_def_proto_depIdxs,
		MessageInfos:      file_kmsp11_tools_p11fn_function_def_proto_msgTypes,
	}.Build()
	File_kmsp11_tools_p11fn_function_def_proto = out.File
	file_kmsp11_tools_p11fn_function_def_proto_rawDesc = nil
	file_kmsp11_tools_p11fn_function_def_proto_goTypes = nil
	file_kmsp11_tools_p11fn_function_def_proto_depIdxs = nil
}
